#!/usr/bin/python3

import sys, os, configparser
args = sys.argv

home = os.path.expanduser("~")

STEAM_COMPAT_APP_ID = str(os.environ.get("STEAM_COMPAT_APP_ID")) 
STEAM_COMPAT_INSTALL_PATH = (str(os.environ.get("STEAM_COMPAT_INSTALL_PATH"))[len(home):]).replace(' ','\ ')

config = configparser.ConfigParser()

f = open('/home/deck/.steam/steam/compatibilitytools.d/HazeCrate/output.log', 'w')
f.write('---------------------------\n')
f.write("APP ID: " + STEAM_COMPAT_APP_ID + '\n')
f.write("INSTALL PATH: " + STEAM_COMPAT_INSTALL_PATH + '\n')
f.write('Args: ' + str(args) + '\n')

executable = ''

options = dict()
for i in range(2, len(args)):
    if args[i][-4:] == '.exe' or args[i][-4:] == '.bat':
        executable = (args[i]).replace('\\','/')
        f.write('Executable: ' + executable + '\n')
    elif args[i][0] == '-':
        if i + 1 < len(args):
            if args[i + 1][0] != '-':
                options[str(args[i])] = (str(args[i + 1])).replace('\\','/')
            else:
                options[str(args[i])] = ''

for k,v in options.items():
    f.write('Key: ' + k + ', Val: ' + v + '\n')

if executable == '':
    executablePath = ''
else:
    executablePath = executable.replace(' ','\ ') + ' '

f.write('exe Path: ' + executablePath + '\n')

if '-conf' in options.keys():
    configPath = (options['-conf']).replace(' ','\ ')
    f.write('config Path: ' + configPath + '\n')


confFullPath = os.path.join(os.getcwd(), configPath)
f.write('Conf full path: ' + confFullPath + '\n')
#c = open(configPath, 'r')
try:
    configFile = open(confFullPath, 'r')
    configData = configFile.read()
except:
    f.write("Couldn't open config\n")


configAutoexec = []
confArray = configData.splitlines()
for line in confArray:
    if((line).lower() == '[autoexec]' or configAutoexec and line):
        if(line[0] == '[' and (line).lower() != '[autoexec]'):
            f.write("End autoexec\n")
            break
        configAutoexec.append(line)
        f.write("Autoexec: " + line + '\n')

try:
    config.read(confFullPath)
except:
    f.write("Couldn't parse config\n")

f.write('CWD: ' + str(os.getcwd()) + '\n')

#f.write(str(c.read()))

try:
    f.write(str(config.sections()) + '\n')
except:
    f.write("Config section couldn't open \n")

f.write("Full Resolution: " + config['sdl']['fullresolution'] + '\n')
#f.write("autoexec: " + str(config['autoexec']) + '\n')

"""
if 'autoexec' in config:
    for k in config['autoexec']:
        f.write("autoexec: " + str(k) + '\n')
"""

cmd = "flatpak run --filesystem=~" + STEAM_COMPAT_INSTALL_PATH + " com.dosbox.DOSBox " + executablePath + ' -conf ' + configPath + ' -exit'
f.write('CMD: ' + cmd + '\n')

#c.close()
f.close()
configFile.close()
os.system(cmd)


"""
CONFIG NOTES

[sdl]

fullscreen=true
fulldouble=true
fullresolution=desktop
windowresolution=original
output=opengl
autolock=true
sensitivity=500
waitonerror=true
priority=higher,normal
mapperfile=mapper.txt
usescancodes=false

[dosbox]

language=
machine=vga
captures=capture
memsize=16

[render]

frameskip=0
aspect=true
scaler=none

"""